language: cpp

# ccache caches obj files between builds
cache: ccache

matrix:
  include:
    - os: linux
      services:
        - docker
      env:
        - BUILD_APIDOC=true
        # Auth token to push API documentation
        - secure: "JKeXk8p65hodb12PVRST6A90swsNubc+46EbSJGSghldIxbFWLBAlwU+KLeOMO4V0veu6k4lnMa50V0UYFZmoUsS6W0aL5Ybo98SpzXHiNLOmOluoqJoF9TBsOTCCRFbWbccgJyVEtulgRcdml96naS51lq9Sw/VO/N3Z472304="
    - os: linux
      services:
        - docker
      env:
        - BUILD_UNITTEST=true
    - os: osx
      osx_image: xcode8.1
      compiler: clang
  allow_failures:
    - env:
      - BUILD_APIDOC=true
      - secure: "JKeXk8p65hodb12PVRST6A90swsNubc+46EbSJGSghldIxbFWLBAlwU+KLeOMO4V0veu6k4lnMa50V0UYFZmoUsS6W0aL5Ybo98SpzXHiNLOmOluoqJoF9TBsOTCCRFbWbccgJyVEtulgRcdml96naS51lq9Sw/VO/N3Z472304="
install:
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      # Download build environment in a docker container
      docker pull freeorion/freeorion-travis-build
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update # Circumvent Ruby runtime error ; see travis-ci/travis-ci#8552
      brew install cmake
      wget --output-document=FreeOrionSDK.dmg https://github.com/freeorion/freeorion-sdk/releases/download/v8/FreeOrionSDK_8_Clang-MacOSX-10.9-x86_64.dmg
      hdiutil attach FreeOrionSDK.dmg
      tar -xjf /Volumes/FreeOrionSDK/dep.tar.bz2 -C Xcode
      hdiutil detach /Volumes/FreeOrionSDK

      # download and setup ccache
      brew install ccache
      export PATH="/usr/local/opt/ccache/libexec:$PATH"
    fi
before_script:
  # Configure git to use the identity of FreeOrion Build Bot and
  # load credentials
  - >
    if [[ "${BUILD_APIDOC}" == "true" ]]; then
      git config --global user.email "freeorionorg@gmail.com"
      git config --global user.name "FreeOrion Build Bot"
      git config --global credential.helper "cache --timeout=300"
      echo -e "url=https://freeorion-bot:${FreeOrion_AUTH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git\n" | git credential approve
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      # Add transparent cmake function to allow possible cross platform use of
      # build sections.
      function cmake {
          docker run -v "${TRAVIS_BUILD_DIR}:/freeorion" -w /freeorion/build freeorion/freeorion-travis-build /usr/bin/cmake $@
      }
    fi
  - mkdir build
  - cd build
  # Setup ccache
  # Make certain ~/.ccache exists
  - mkdir -p $HOME/.ccache
  - echo sloppiness = file_macro > $HOME/.ccache/ccache.conf
  - ccache --version
  - ccache --show-stats
before_cache:
  # Check ccache
  - ccache --show-stats
script:
  - >
    if [[ "${BUILD_APIDOC}" == "true" && "${TRAVIS_BRANCH}" == "master" ]]; then
      cmake ..
      cmake --build . --target cpp-apidoc

      git clone --depth=1 --branch=master https://github.com/freeorion/freeorion.github.io.git apidoc-deploy.git
      pushd apidoc-deploy.git
      rm -rf cppapi/master
      mkdir -p cppapi/master
      cp -R ../doc/cpp-apidoc/html cppapi/master
      git add -A cppapi/master
      git commit -m "Update FreeOrion API documentation to match commit \`$(date --iso-8601).${TRAVIS_COMMIT:0:8}\`"
      git push https://github.com/freeorion/freeorion.github.io.git master:master
      popd
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${BUILD_UNITTEST}" == "true" ]]; then
      cmake -DBUILD_TESTING=ON ..
      cmake --build . -- -j 2 &&
      cmake --build . --target unittest &&
      cd ../default &&
      python -m compileall -q .
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "osx" && -z "${BUILD_APIDOC}" ]]; then
      cmake -GXcode ..
      cmake --build . --config Release -- -parallelizeTargets -jobs $(sysctl hw.ncpu | awk '{print $2}')
    fi
